on:
  push:
    branches: [main, staging, trying]
  pull_request:
    branches: [main]

name: Test

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: miri, fuzz

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Test SIMD
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features simd

      - name: Miri
        uses: actions-rs/cargo@v1
        with:
          command: miri
          args: test

      - name: Fuzz
        uses: actions-rs/cargo@v1
        with:
          command: fuzz
          args: run parse -- -runs=500000
